/* ISO 3166 Codes (Countries)*/

INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Afghanistan', 'Afeganistão', 'AF')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Aland Islands', 'Ilhas Aland', 'AX')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Albania', 'Albânia', 'AL')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Algeria', 'Argélia', 'DZ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('American Samoa', 'Samoa Americana', 'AS')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Andorra', 'Andorra', 'AD')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Angola', 'Angola', 'AO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Anguilla', 'Anguilla', 'AI')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Antarctica', 'Antártida', 'AQ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Antigua and Barbuda', 'Antigua e Barbuda', 'AG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Argentina', 'Argentina', 'AR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Armenia', 'Armênia', 'AM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Aruba', 'Aruba', 'AW')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Australia', 'Austrália', 'AU')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Austria', 'Áustria', 'AT')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Azerbaijan', 'Azerbaijão', 'AZ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Bahamas', 'Bahamas', 'BS')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Bahrain', 'Bahrein', 'BH')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Bangladesh', 'Bangladesh', 'BD')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Barbados', 'Barbados', 'BB')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Belarus', 'Belarus', 'BY')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Belgium', 'Bélgica', 'BE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Belize', 'Belize', 'BZ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Benin', 'Benin', 'BJ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Bermuda', 'Bermudas', 'BM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Bhutan', 'Butão', 'BT')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Bolivia', 'Bolívia', 'BO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Bonaire, Sint Eustatius an Saba', 'Bonaire, Santo Eustáquio e Saba', 'BQ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Bosnia and Herzegowina', 'Bósnia-herzegovina', 'BA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Botswana', 'Botsuana', 'BW')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Bouvet Island', 'Ilha Bouvet', 'BV')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Brazil', 'Brasil', 'BR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('British Indian Ocean Territory', 'Território Britânico do Oceano Indico', 'IO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Brunei Darussalam', 'Brunei', 'BN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Bulgaria', 'Bulgária', 'BG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Burkina Faso', 'Burkina Faso', 'BF')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Burundi', 'Burundi', 'BI')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Cabo Verde', 'Cabo Verde', 'CV')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Cambodia', 'Camboja', 'KH')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Cameroon', 'Camarões', 'CM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Canada', 'Canadá', 'CA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Cayman Islands', 'Ilhas Cayman', 'KY')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Central African Republic', 'Republica Centro-Africana', 'CF')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Chad', 'Chade', 'TD')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Chile', 'Chile', 'CL')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('China', 'China', 'CN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Christmas Island', 'Ilha Christmas', 'CX')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Cocos (Keeling) Islands', 'Ilhas Cocos (Keeling)', 'CC')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Colombia', 'Colômbia', 'CO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Comoros', 'Ilhas Comores', 'KM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Congo, the Democratic Republic of the', 'Republica Democrática do Congo', 'CD')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Congo', 'Congo', 'CG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Cook Islands', 'Ilhas Cook', 'CK')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Costa Rica', 'Costa Rica', 'CR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Cote dIvoire', 'Costa do Marfim', 'CI')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Croatia', 'Croácia', 'HR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Cuba', 'Cuba', 'CU')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Cyprus', 'Chipre', 'CY')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Czech Republic', 'Republica Tcheca', 'CZ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Denmark', 'Dinamarca', 'DK')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Djibouti', 'Djibuti', 'DJ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Dominica', ' IlhaDominica', 'DM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Dominican Republic', 'Republica Dominicana', 'DO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Ecuador', 'Equador', 'EC')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Egypt', 'Egito', 'EG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('El Salvador', 'El Salvador', 'SV')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Equatorial Guinea', 'Guine-Equatorial', 'GQ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Eritrea', 'Eritreia', 'ER')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Estonia', 'Estônia', 'EE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Ethiopia', 'Etiópia', 'ET')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Falkland Islands (Malvinas)', 'Falkland (Ilhas Malvinas)', 'FK')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Faroe Islands', 'Ilhas Feroe', 'FO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Fiji', 'Fiji', 'FJ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Finland', 'Finlândia', 'FI')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('France', 'França', 'FR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('French Guiana', 'Guiana francesa', 'GF')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('French Polynesia', 'Polinésia Francesa', 'PF')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('French Southern Territories', 'Terras Austrais e Antárticas Francesas', 'TF')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Gabon', 'Gabão', 'GA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Gambia', 'Gambia', 'GM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Georgia', 'Georgia', 'GE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Germany', 'Alemanha', 'DE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Ghana', 'Gana', 'GH')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Gibraltar', 'Gibraltar', 'GI')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Greece', 'Grécia', 'GR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Greenland', 'Groenlândia', 'GL')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Grenada', 'Granada', 'GD')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Guadeloupe', 'Guadalupe', 'GP')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Guam', 'Guam', 'GU')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Guatemala', 'Guatemala', 'GT')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Guinea', 'Guine', 'GN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Guinea-Bissau', 'Guine-Bissau', 'GW')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Guyana', 'Guiana', 'GY')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Haiti', 'Haiti', 'HT')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Heard and Mc Donald Islands', 'Ilha Heard e Ilhas McDonald', 'HM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Holy See (Vatican City State)', 'Estado da Cidade do Vaticano', 'VA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Honduras', 'Honduras', 'HN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Hong Kong', 'Hong Kong', 'HK')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Hungary', 'Hungria', 'HU')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Iceland', 'Islândia', 'IS')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('India', 'Índia', 'IN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Indonesia', 'Indonésia', 'ID')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Iran (Islamic Republic of)', 'Republica Islâmica do Irã', 'IR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Iraq', 'Iraque', 'IQ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Ireland', 'Irlanda', 'IE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Isle of Man', 'Ilha de Man', 'IM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Israel', 'Israel', 'IL')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Italy', 'Itália', 'IT')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Jamaica', 'Jamaica', 'JM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Japan', 'Japão', 'JP')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Jordan', 'Jordânia', 'JO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Kazakhstan', 'Cazaquistão', 'KZ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Kenya', 'Quênia', 'KE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Kiribati', 'Kiribati', 'KI')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Korea, Democratic Peoples Republic of', 'Republica Popular Democrática da Coreia', 'KP')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Korea, Republic of', 'Republica da Coreia', 'KR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Kuwait', 'Kuwait', 'KW')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Kyrgyzstan', 'Quirguistão', 'KG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Lao Peoples Democratic Republic', 'Republica Popular Democrática do Laos', 'LA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Latvia', 'Letônia', 'LV')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Lebanon', 'Líbano', 'LB')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Lesotho', 'Lesoto', 'LS')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Liberia', 'Libéria', 'LR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Libyan Arab Jamahiriya', 'Líbia', 'LY')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Liechtenstein', 'Liechtenstein', 'LI')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Lithuania', 'Lituânia', 'LT')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Luxembourg', 'Luxemburgo', 'LU')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Macao', 'Macau', 'MO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Madagascar', 'Madagascar', 'MG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Malawi', 'Malavi', 'MW')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Malaysia', 'Malásia', 'MY')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Maldives', 'Maldivas', 'MV')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Mali', 'Mali', 'ML')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Malta', 'Malta', 'MT')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Marshall Islands', 'Ilhas Marshall', 'MH')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Martinique', 'Martinica', 'MQ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Mauritania', 'Mauritânia', 'MR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Mauritius', 'Mauricio', 'MU')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Mayotte', 'Mayotte (Ilhas Francesas)', 'YT')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Mexico', 'México', 'MX')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Micronesia', 'Micronesia', 'FM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Moldova, Republic of', 'Republica da Moldávia', 'MD')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Monaco', 'Mônaco', 'MC')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Mongolia', 'Mongólia', 'MN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Montenegro', 'Montenegro', 'ME')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Montserrat', 'Montserrat, Ilhas', 'MS')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Morocco', 'Marrocos', 'MA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Mozambique', 'Moçambique', 'MZ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Myanmar', 'Mianmar (Birmânia)', 'MM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Namibia', 'Namíbia', 'NA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Nauru', 'Nauru', 'NR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Nepal', 'Nepal', 'NP')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Netherlands', 'Países Baixos (Holanda)', 'NL')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('New Caledonia', 'Nova Caledonia', 'NC')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('New Zealand', 'Nova Zelândia', 'NZ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Nicaragua', 'Nicarágua', 'NI')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Niger', 'Níger', 'NE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Nigeria', 'Nigéria', 'NG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Niue', 'Niue, Ilha', 'NU')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Norfolk Island', 'Ilha Norfolk', 'NF')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('North Macedonia', 'Macedônia', 'mk')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Northern Mariana Islands', 'Ilhas Mariana do Norte', 'MP')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Norway', 'Noruega', 'NO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Oman', 'Oma', 'OM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Pakistan', 'Paquistão', 'PK')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Palau', 'Palau', 'PW')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Panama', 'Panamá', 'PA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Papua New Guinea', 'Papua Nova Guine', 'PG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Paraguay', 'Paraguai', 'PY')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Peru', 'Peru', 'PE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Philippines', 'Filipinas', 'PH')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Pitcairn', 'Pitcairn', 'PN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Poland', 'Polônia', 'PL')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Portugal', 'Portugal', 'PT')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Puerto Rico', 'Porto Rico', 'PR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Qatar', 'Catar', 'QA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Reunion', 'Reunião, Ilha', 'RE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Romania', 'Romênia', 'RO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Russian Federation', 'Rússia', 'RU')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Rwanda', 'Ruanda', 'RW')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Saint Barthélemy', 'São Bartolomeu', 'BL')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Saint Heleny', 'Santa Helena', 'SH')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Saint Kitts and Nevis', 'São Cristovão e Neves', 'KN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Saint Lucia', 'Santa Lucia', 'LC')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Saint Martin (partie française)', 'São Martin (parte francesa)', 'MF')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Saint Pierre and Miquelon', 'São Pedro e Miquelon', 'PM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Saint Vincent and the Grenadines', 'São Vicente e Granadinas', 'VC')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Samoa', 'Samoa', 'WS')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('San Marino', 'San Marino', 'SM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Sao Tome and Principe', 'São Tome e Príncipe', 'ST')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Saudi Arabia', 'Arábia Saudita', 'SA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Senegal', 'Senegal', 'SN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Serbia', 'Sérvia', 'RS')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Seychelles', 'Seychelles', 'SC')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Sierra Leone', 'Serra Leoa', 'SL')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Singapore', 'Cingapura', 'SG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Sint Maarten (Dutch part)', 'São Martin (parte holandesa)', 'MF')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Slovakia (Slovak Republic)', 'Republica Eslovaca', 'SK')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Slovenia', 'Eslovênia', 'SI')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Solomon Islands', 'Ilhas Salomão', 'SB')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Somalia', 'Somália', 'SO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('South Africa', 'África do Sul', 'ZA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('South Georgia and the South Sandwich Islands', 'Ilhas Geórgia do Sul e Sandwich do Sul', 'GS')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Spain', 'Espanha', 'ES')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Sri Lanka', 'Sri Lanka', 'LK')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Sudan', 'Sudão', 'SD')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Suriname', 'Suriname', 'SR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Svalbard and Jan Mayen Islands', 'Ilhas Svalbard e Jan Mayen', 'SJ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Sweden', 'Suécia', 'SE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Switzerland', 'Suíça', 'CH')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Syrian Arab Republic', 'Republica Árabe da Síria', 'SY')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Taiwan, Province of China', 'Taiwan Provincia da China', 'TW')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Tajikistan', 'Tadjiquistao', 'TJ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Tanzania, United Republic of', 'Republica Unida da Tanzânia', 'TZ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Thailand', 'Tailândia', 'TH')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Timor-Leste', 'Timor-Leste', 'TL')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Togo', 'Togo', 'TG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Tokelau', 'Toquelau, Ilhas', 'TK')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Tonga', 'Tonga', 'TO')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Trinidad and Tobago', 'Trinidad e Tobago', 'TT')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Tunisia', 'Tunísia', 'TN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Turkey', 'Turquia', 'TR')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Turkmenistan', 'Turcomenistão', 'TM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Turks and Caicos Islands', 'Ilhas Turcas e Caicos', 'TC')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Tuvalu', 'Tuvalu', 'TV')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Uganda', 'Uganda', 'UG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Ukraine', 'Ucrânia', 'UA')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('United Arab Emirates', 'Emirados Árabes Unidos', 'AE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('United Kingdom', 'Reino Unido', 'GB')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('United States Minor Outlying Islands', 'Ilhas Menores Distantes dos Estados Unidos', 'UM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('United States', 'Estados Unidos', 'US')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Uruguay', 'Uruguai', 'UY')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Uzbekistan', 'Uzbequistão', 'UZ')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Vanuatu', 'Vanuatu', 'VU')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Venezuela', 'Venezuela', 'VE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Viet Nam', 'Vietnã', 'VN')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Virgin Islands (British)', 'Ilhas Virgens (Britânicas)', 'VG')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Virgin Islands (U.S.)', 'Ilhas Virgens(E.U.A.)', 'VI')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Wallis and Futuna', 'Wallis e Futuna', 'WF')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Western Sahara', 'Saara Ocidental', 'EH')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Yemen', 'Iémen', 'YE')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Zambia', 'Zâmbia', 'ZM')
INSERT INTO t_country (country_name,country_pt_br,country_initials_alfa_2) VALUES('Zimbabwe', 'Zimbabue', 'ZW')