INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Acre','AC',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Alagoas','AL',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Amapá','AP',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Amazonas','AM',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Bahia','BA',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Ceará','CE',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Distrito Federal','DF',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Espírito Santo','ES',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Goiás','GO',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Maranhão','MA',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Mato Grosso','MT',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Mato Grosso do Sul','MS',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Minas Gerais','MG',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Paraná','PR',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Paraíba','PB',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Pará','PA',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Pernambuco','PE',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Piauí','PI',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Rio Grande do Norte','RN',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Rio Grande do Sul','RS',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Rio de Janeiro','RJ',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Rondônia','RO',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Roraima','RR',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Santa Catarina','SC',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Sergipe','SE',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('São Paulo','SP',32)
INSERT INTO t_state (state_name, state_initials,country_id) VALUES('Tocantis','TO',32)